spring:
  application:
    name: user

  config:
    import: optional:classpath:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/asset-control?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true

    serviceUrl:
      defaultZone: http://localhost:8761/eureka/