spring:
  config:
    import: optional:classpath:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/asset-control?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none