spring:
  application:
    name: auth

  flyway:
    enabled: true

  profiles:
    active: mysql

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true

    serviceUrl:
      defaultZone: http://localhost:8761/eureka/